"""Created completed_tasks table

Revision ID: 54a09521febb
Revises: ed63e0807ada
Create Date: 2025-05-12 14:52:04.886024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54a09521febb'
down_revision: Union[str, None] = 'ed63e0807ada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completed_tasks',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('date_and_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('employee_id', 'shop_id', 'date_and_time')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('completed_tasks')
    # ### end Alembic commands ###
