"""initial

Revision ID: ed63e0807ada
Revises: 
Create Date: 2025-04-28 17:29:16.526619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed63e0807ada'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('fn', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.CheckConstraint("fn ~ '^[0-9]{16}$'", name='fn_length_constraint'),
    sa.PrimaryKeyConstraint('shop_id', 'fn')
    )
    op.create_table('used_checks',
    sa.Column('fp', sa.BigInteger(), nullable=False),
    sa.Column('fn', sa.String(), nullable=False),
    sa.Column('i', sa.BigInteger(), nullable=False),
    sa.Column('t', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("fn ~ '^[0-9]{16}$'", name='fn_length_constraint'),
    sa.CheckConstraint('fp BETWEEN 0 AND 9999999999', name='fp_length_constraint'),
    sa.CheckConstraint('i BETWEEN 0 AND 9999999999', name='i_length_constraint'),
    sa.PrimaryKeyConstraint('fp', 'fn')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('used_checks')
    op.drop_table('shops')
    # ### end Alembic commands ###
